/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Comic;
import BLL.Detalle;
import BLL.Venta;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fernando
 */
public class JpnlIngresoVenta extends javax.swing.JPanel {
private DefaultListModel dm = new DefaultListModel();
private Comic cc;
private ArrayList<Comic> cl;
    /**
     * Creates new form JpnlIngresoVenta
     */
    public JpnlIngresoVenta() {
        initComponents();
        initComponents();
        cc = new Comic();
        cl = new ArrayList<>();
        this.setJlst_productoBodega();
    }
     public void setJlst_productoBodega() {
        DefaultListModel dl = new DefaultListModel();
        for(Comic c:cc.readBodega()) {
            dl.addElement(c.getNombre()+" "+c.getCodigo());
        }
        this.jlst_productoBodega.setModel(dl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlst_productoBodega = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlst_productoComprar = new javax.swing.JList();
        jbtn_flecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtn_vender = new javax.swing.JButton();
        jtxt_idVenta = new javax.swing.JTextField();
        jtxt_rutCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Productos en bodega");

        jlst_productoBodega.setVisibleRowCount(7);
        jlst_productoBodega.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlst_productoBodegaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jlst_productoBodega);

        jLabel4.setText("Productos a comprar");

        jlst_productoComprar.setVisibleRowCount(7);
        jScrollPane2.setViewportView(jlst_productoComprar);

        jbtn_flecha.setText("-->");
        jbtn_flecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_flechaActionPerformed(evt);
            }
        });

        jLabel1.setText("Id venta");

        jbtn_vender.setText("Vender");
        jbtn_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_venderActionPerformed(evt);
            }
        });

        jLabel2.setText("Rut Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxt_idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxt_rutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jbtn_flecha)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jbtn_vender, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jtxt_idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jtxt_rutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jbtn_flecha))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jbtn_vender))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlst_productoBodegaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlst_productoBodegaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jlst_productoBodegaAncestorAdded

    private void jbtn_flechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_flechaActionPerformed
        // TODO add your handling code here:
        dm.addElement(this.jlst_productoBodega.getSelectedValue());
        this.jlst_productoComprar.setModel(dm);
        cl.add(cc.readBodega().get(this.jlst_productoBodega.getSelectedIndex()));
    }//GEN-LAST:event_jbtn_flechaActionPerformed

    private void jbtn_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_venderActionPerformed
        // TODO add your handling code here:
        Venta v = new Venta();
        v.setIdVenta(Integer.valueOf(this.jtxt_idVenta.getText()));
        v.setRut(Integer.valueOf(this.jtxt_rutCliente.getText()));
        
        String pop = v.create(v);
        
        
        for (Comic c:cl) {
            Detalle d = new Detalle();
            d.setCodigoComic(c.getCodigo());
            d.setId_venta(v.getIdVenta());
            new Detalle().create(d);
        }
        JOptionPane.showMessageDialog(null, pop );
    }//GEN-LAST:event_jbtn_venderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_flecha;
    private javax.swing.JButton jbtn_vender;
    private javax.swing.JList jlst_productoBodega;
    private javax.swing.JList jlst_productoComprar;
    private javax.swing.JTextField jtxt_idVenta;
    private javax.swing.JTextField jtxt_rutCliente;
    // End of variables declaration//GEN-END:variables
}
