/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Main;

import GUI.JpnlInforme;
import GUI.JpnlIngresoCliente;
import GUI.JpnlIngresoComic;
import GUI.JpnlIngresoVenta;
import GUI.JpnlTablaClientes;
import GUI.JpnlTablaPorNombre;
import GUI.JpnlTablaTodo;
import GUI.JpnlTablaVentaPorCodigo;

/**
 *
 * @author fernando
 */
public class JfrmMain extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMain
     */
    public JfrmMain() {
        initComponents();
    }
   
   
    public void cambioVentana(javax.swing.JPanel jp){
        System.out.println("2");
        this.jpnl_main.removeAll();
        jp.setSize(this.jpnl_main.getSize());
        this.jpnl_main.add(jp);
        this.jpnl_main.repaint();
        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_main = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmnu_comic = new javax.swing.JMenuItem();
        jmnu_cliente = new javax.swing.JMenuItem();
        jmnu_venta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmnu_verRevistas = new javax.swing.JMenuItem();
        jmnu_verClientes = new javax.swing.JMenuItem();
        jmnu_verVentas = new javax.swing.JMenuItem();
        jmnu_verInforme = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnl_main.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpnl_mainLayout = new javax.swing.GroupLayout(jpnl_main);
        jpnl_main.setLayout(jpnl_mainLayout);
        jpnl_mainLayout.setHorizontalGroup(
            jpnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        jpnl_mainLayout.setVerticalGroup(
            jpnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        jMenu1.setText("Ingresos");

        jmnu_comic.setText("Comics");
        jmnu_comic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnu_comicActionPerformed(evt);
            }
        });
        jMenu1.add(jmnu_comic);

        jmnu_cliente.setText("Clientes");
        jmnu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnu_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmnu_cliente);

        jmnu_venta.setText("Ventas");
        jmnu_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnu_ventaActionPerformed(evt);
            }
        });
        jMenu1.add(jmnu_venta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vistas");

        jmnu_verRevistas.setText("Revistas");
        jmnu_verRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnu_verRevistasActionPerformed(evt);
            }
        });
        jMenu2.add(jmnu_verRevistas);

        jmnu_verClientes.setText("Clientes");
        jmnu_verClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnu_verClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jmnu_verClientes);

        jmnu_verVentas.setText("Ventas");
        jmnu_verVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnu_verVentasActionPerformed(evt);
            }
        });
        jMenu2.add(jmnu_verVentas);

        jmnu_verInforme.setText("Informe");
        jmnu_verInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnu_verInformeActionPerformed(evt);
            }
        });
        jMenu2.add(jmnu_verInforme);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Buscar");

        jMenuItem8.setText("Comic por nombre");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnl_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnl_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnu_comicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnu_comicActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlIngresoComic());

       
    }//GEN-LAST:event_jmnu_comicActionPerformed

    private void jmnu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnu_clienteActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlIngresoCliente());
        
    }//GEN-LAST:event_jmnu_clienteActionPerformed

    private void jmnu_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnu_ventaActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlIngresoVenta());
    }//GEN-LAST:event_jmnu_ventaActionPerformed

    private void jmnu_verInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnu_verInformeActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlInforme());
    }//GEN-LAST:event_jmnu_verInformeActionPerformed

    private void jmnu_verRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnu_verRevistasActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlTablaTodo());
    }//GEN-LAST:event_jmnu_verRevistasActionPerformed

    private void jmnu_verClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnu_verClientesActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlTablaClientes());
    }//GEN-LAST:event_jmnu_verClientesActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlTablaPorNombre());
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jmnu_verVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnu_verVentasActionPerformed
        // TODO add your handling code here:
        this.cambioVentana(new JpnlTablaVentaPorCodigo());
    }//GEN-LAST:event_jmnu_verVentasActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jmnu_cliente;
    private javax.swing.JMenuItem jmnu_comic;
    private javax.swing.JMenuItem jmnu_venta;
    private javax.swing.JMenuItem jmnu_verClientes;
    private javax.swing.JMenuItem jmnu_verInforme;
    private javax.swing.JMenuItem jmnu_verRevistas;
    private javax.swing.JMenuItem jmnu_verVentas;
    private javax.swing.JPanel jpnl_main;
    // End of variables declaration//GEN-END:variables
}
